module Akephalos
  class Client
    # Listener for events generated by the provided WebClient instance. In
    # particular, we listen for changes to the content of the current window to
    # update the client's current page.
    class Listener
      include com.gargoylesoftware.htmlunit.WebWindowListener

      # @param [Akephalos::Client] client instance to update on events
      def initialize(client)
        @client = client
      end

      # No-op. Required for API compatibility
      #
      # @api htmlunit
      def webWindowClosed(event)
      end

      # Update client with the event's page
      #
      # @api htmlunit
      def webWindowContentChanged(event)
        @client.page = event.getNewPage
      end
    end
  end
end
